version: '2'
services:
  urss:
    build: .
    ports:
     - "4242:4242"
    depends_on:
     - db
    network_mode: "host"
    restart: "always"
  db:
    image: mongo:3.0.4
    volumes:
      - "/data/db"
    ports:
      - "27017:27017"
    network_mode: "host"
    restart: "always"
