version: '2'
services:
  db:
    image: mongo:3.0.4
    volumes:
      - "/data/db"
    ports:
      - "27017:27017"
    network_mode: "host"
    restart: "always"
  seed-db:
    build: ./script/seed-db
    network_mode: "host"
    depends_on:
      - db
  urss:
    build: .
    ports:
     - "4242:4242"
    depends_on:
     - db
    network_mode: "host"
    restart: "always"
  front-db:
    image: mrvautin/adminmongo:latest
    ports:
      - "1234:1234"
    depends_on:
      - db
    network_mode: "host"
    restart: "always"
  urss-web:
    build: ./script/urss-web
    ports:
      - "8000:8000"
    depends_on:
      - urss
    network_mode: "host"
    restart: "always"
